apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: "karpenter-provisioner-workload-intensive-memory"
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["r5a.large", "r5a.xlarge", "r5a.2xlarge", "r5a.4xlarge", "r5.large", "r5.xlarge", "r5.2xlarge", "r5.4xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  provider:
    instanceProfile: "KarpenterNodeInstanceProfile-cluster-spark-on-aws-eks-dev"
    subnetSelector:
        Name: "*spark-on-aws-eks-dev-private*"
    securityGroupSelector:
        Name: "cluster-spark-on-aws-eks-dev-eks_worker_sg"
  ttlSecondsAfterEmpty: 30