apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: "karpenter-provisioner-high-priority"
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["t3.medium", "t3.large", "t3.2xlarge", "m5.4xlarge", "m5.8xlarge"]
    - key: "kubernetes.io/arch" 
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  provider:
    instanceProfile: "KarpenterNodeInstanceProfile-cluster-spark-on-aws-eks-dev"
    subnetSelector:
        Name: "*spark-on-aws-eks-dev-private*"
    securityGroupSelector:
        Name: "cluster-spark-on-aws-eks-dev-eks_worker_sg"
  ttlSecondsAfterEmpty: 30